### ISSUE TITLE
eglibc support is ending soon

### ISSUE THREAD

**Issue by thagabe** [jdub/openwrt-systemd#3]
This is the last eglibc release, should we look into incorporating glibc to trunk openwrt and as an extension this project? Also would you like to merge the projects then I'll transfer the repo to you, I don't have the time and experience to run this awesome project :p however I will try my best to contribute!

**Comment by jdub** [comment]
Holy shit, packaging glibc? I touch one weird combination of interesting projects and it blows up in my face like this?! ;-)

**Comment by jdub** [comment]
So, what are we looking at?

eglibc-2.19-r25243.tar.bz2 = 19M
glibc-2.21.tar.bz2 = 18M (though glibc-2.21.tar.xz is 12M)

There's about 1112 lines of build config for eglibc, not including the 10 patches for two supported versions.

A list of [what wasn't merged back to glibc](http://www.eglibc.org/archives/patches/msg01327.html) as of February 2014.

What matches eglibc in OpenWrt? Might not all be relevant, but it gives an impression.

```
./config/Config-build.in
./docs/working.tex
./feeds/packages/devel/diffutils/Makefile
./feeds/packages/lang/luaposix/Makefile
./feeds/packages/lang/perl/Config.in
./feeds/packages/lang/perl/Makefile
./feeds/packages/lang/perl/perlmod.mk
./feeds/packages/net/transmission/patches/010_libtransmission_fallocate64_eglibc.patch
./feeds/packages/utils/pciutils/Makefile
./feeds/systemd/README.md
./feeds/systemd/systemd/Makefile
./feeds/telephony/libs/re/Makefile
./feeds/telephony/net/freeswitch/Makefile
./include/package-defaults.mk
./include/version.mk
./package/devel/perf/Makefile
./package/libs/libbsd/Makefile
./package/libs/toolchain/Makefile
./package/network/services/hostapd/Makefile
./package/network/services/igmpproxy/Makefile
./package/network/services/lldpd/Makefile
./package/network/services/samba36/Makefile
./package/network/utils/iproute2/Makefile
./package/network/utils/iputils/Makefile
./package/system/fstools/Makefile
./package/system/procd/Makefile
./package/system/ubox/Makefile
./package/utils/lua/Makefile
./scripts/ext-toolchain.sh
./target/linux/arm64/README
./target/toolchain/files/wrapper.sh
./toolchain/Config.in
./toolchain/eglibc/common.mk
./toolchain/eglibc/config/Config.in
./toolchain/eglibc/Config.in
./toolchain/eglibc/Config.version
./toolchain/eglibc/patches/2.19/300-require-autoconf-2.69.patch
```

Had a quick look to see if anyone was working on it, but didn't come up with anything obvious. So, I'm going to copy eglibc, take out the noise, and have a play. :-)

**Comment by jdub** [comment]
So, I have `make menuconfig` working (no build options yet), and am doing a `make toolchain/prepare` right now. Let's see how it goes. :smiley:

**Comment by jdub** [comment]
<img src=http://i.imgur.com/vwMin.gif>
- [x] copypasta eglibc to glibc
- [x] get rid of legacy eglibc mess
- [x] make basic s#eglibc#glibc#i changes
- [x] integrate into OpenWrt menu + config
- [x] `make menuconfig`
- [x] `make menuconfig` with glibc selected
- [x] `make toolchain/prepare`
- [x] `make toolchain/install` :zzz: 

Track my progress: https://github.com/jdub/openwrt/tree/glibc :boom:

**Comment by jdub** [comment]
Not a massive size difference, and that's _without_ any interesting configuration options involved.

```
eglibc-2.19:
-rwxr-xr-x    1 root     root       14.2K Feb 17  2015 /lib/libanl-2.19.so
-rwxr-xr-x    1 root     root        1.3M Feb 17  2015 /lib/libc-2.19.so
-rwxr-xr-x    1 root     root      178.8K Feb 17  2015 /lib/libcidn-2.19.so
-rwxr-xr-x    1 root     root       34.9K Feb 17  2015 /lib/libcrypt-2.19.so
-rwxr-xr-x    1 root     root       10.4K Feb 17  2015 /lib/libdl-2.19.so
-rwxr-xr-x    1 root     root      820.5K Feb 17  2015 /lib/libm-2.19.so
-rwxr-xr-x    1 root     root       18.0K Feb 17  2015 /lib/libnss_dns-2.19.so
-rwxr-xr-x    1 root     root       49.0K Feb 17  2015 /lib/libnss_files-2.19.so
-rwxr-xr-x    1 root     root      107.4K Feb 17  2015 /lib/libpthread-2.19.so
-rwxr-xr-x    1 root     root       73.8K Feb 17  2015 /lib/libresolv-2.19.so
-rwxr-xr-x    1 root     root       32.4K Feb 17  2015 /lib/librt-2.19.so
-rwxr-xr-x    1 root     root        9.8K Feb 17  2015 /lib/libutil-2.19.so

glibc-2.21:
-rwxr-xr-x 1 jdub jdub  15K Feb 20 08:15 ./lib/libanl-2.21.so
-rwxr-xr-x 1 jdub jdub 1.4M Feb 20 08:15 ./lib/libc-2.21.so
-rwxr-xr-x 1 jdub jdub 179K Feb 20 08:15 ./lib/libcidn-2.21.so
-rwxr-xr-x 1 jdub jdub  35K Feb 20 08:15 ./lib/libcrypt-2.21.so
-rwxr-xr-x 1 jdub jdub  11K Feb 20 08:15 ./lib/libdl-2.21.so
-rwxr-xr-x 1 jdub jdub 821K Feb 20 08:15 ./lib/libm-2.21.so
-rwxr-xr-x 1 jdub jdub  18K Feb 20 08:15 ./lib/libnss_dns-2.21.so
-rwxr-xr-x 1 jdub jdub  49K Feb 20 08:15 ./lib/libnss_files-2.21.so
-rwxr-xr-x 1 jdub jdub 108K Feb 20 08:15 ./lib/libpthread-2.21.so
-rwxr-xr-x 1 jdub jdub  74K Feb 20 08:15 ./lib/libresolv-2.21.so
-rwxr-xr-x 1 jdub jdub  33K Feb 20 08:15 ./lib/librt-2.21.so
-rwxr-xr-x 1 jdub jdub 9.8K Feb 20 08:15 ./lib/libutil-2.21.so
```

**Comment by jdub** [comment]
That didn't seem so hard. I'm going to rebase and tidy up my commits for submission to OpenWrt. :-) Will close this for now. That's for suggesting it!
