### ISSUE TITLE
complete beginner manual

### ISSUE THREAD

**Issue by zabbal** [jdub/openwrt-systemd#4]
Would be excellent if there were some manual (blog post?) which starts from VoCore an describes all the steps to get it booted with systemd:
- connect VoCore to laptop
- install OpenWRT on it
- install systemd
- configure and boot 
- try various goodies (journald, bootchart, networkd...)

If something like that will hit http://vocore.io/wiki/index than I expect multitude of eager new user and hence better QA for the project and higher chance to get more contributors on board.

**Comment by jdub** [comment]
Hi -- I'll definitely blog about the project (and link to it), but I don't regard lack of beginner documentation covering everything from the VoCore through OpenWrt and systemd as an issue/feature for this project. But thanks, and I'll check out your other issues now.
